//
//  PasteboardSnapshot.swift
//  Otto
//
//  A full copy of the user's clipboard, taken before Otto pastes an answer through it and put back
//  afterwards, plus the nspasteboard.org markers that keep Otto's temporary write out of clipboard
//  managers. A password manager's item is never copied: Otto clears it after the paste instead.
//

import AppKit
import Foundation

/// A full copy of a pasteboard's items (every type's data), for putting the user's clipboard back.
struct PasteboardSnapshot: Equatable {
    /// What `capture` found.
    enum Capture: Equatable {
        case captured(PasteboardSnapshot)
        /// An item carries `org.nspasteboard.ConcealedType` (or a password manager's own type): no bytes are kept,
        /// and after the paste the clipboard is cleared instead of restored.
        case concealed
        /// Over the byte limit, or holds file promises: nothing is kept and the answer replaces the clipboard.
        case unrestorable
    }

    static let defaultByteLimit = 64 * 1024 * 1024

    let items: [[NSPasteboard.PasteboardType: Data]]
    let changeCount: Int
    let totalBytes: Int

    private static let promiseTypes: Set<String> = [
        "com.apple.NSFilePromiseItemMetaData",
        "com.apple.pasteboard.promised-file-url",
        "com.apple.pasteboard.promised-file-content-type",
    ]

    /// Password managers mark their copies concealed so clipboard tools skip them.
    static func isConcealed(_ type: NSPasteboard.PasteboardType) -> Bool {
        let raw = type.rawValue
        return type == ClipboardMarkers.concealed || raw.hasPrefix("com.agilebits.")
            || raw.lowercased().contains("password")
    }

    /// `.concealed` for password-manager items (checked from the type list alone, before any data is read);
    /// `.unrestorable` when the data exceeds `byteLimit` or contains file promises.
    static func capture(_ pasteboard: NSPasteboard, byteLimit: Int = defaultByteLimit) -> Capture {
        let changeCount = pasteboard.changeCount
        let pasteboardItems = pasteboard.pasteboardItems ?? []
        let types = pasteboardItems.flatMap(\.types)
        if types.contains(where: isConcealed) { return .concealed }
        if types.contains(where: { promiseTypes.contains($0.rawValue) }) { return .unrestorable }

        var items: [[NSPasteboard.PasteboardType: Data]] = []
        var totalBytes = 0
        for item in pasteboardItems {
            var copy: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                guard let data = item.data(forType: type) else { continue }
                totalBytes += data.count
                if totalBytes > byteLimit { return .unrestorable }
                copy[type] = data
            }
            items.append(copy)
        }
        return .captured(PasteboardSnapshot(items: items, changeCount: changeCount, totalBytes: totalBytes))
    }

    /// clearContents + writeObjects(NSPasteboardItem…); also writes `org.nspasteboard.TransientType`
    /// (empty data) so clipboard managers don't log the restore as a new copy. Returns the new changeCount.
    @discardableResult func restore(to pasteboard: NSPasteboard) -> Int {
        pasteboard.clearContents()
        let objects: [NSPasteboardItem] = items.enumerated().map { index, types in
            let item = NSPasteboardItem()
            for (type, data) in types { item.setData(data, forType: type) }
            if index == 0 { item.setData(Data(), forType: ClipboardMarkers.transient) }
            return item
        }
        if !objects.isEmpty { pasteboard.writeObjects(objects) }
        return pasteboard.changeCount
    }
}

enum ClipboardMarkers {
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")   // "com.jalenedusei.otto"
    static let sourceIdentifier = "com.jalenedusei.otto"

    /// Writes a PastePayload as ONE NSPasteboardItem: .rtf, .html, .string (+ markers). Returns changeCount.
    /// `transient` marks Otto's temporary paste write (transient + auto-generated) so clipboard managers skip
    /// it; a copy the user keeps is written without those two markers.
    @discardableResult
    static func write(_ payload: PastePayload, to pasteboard: NSPasteboard, transient: Bool) -> Int {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        if let rtf = payload.rtf { item.setData(rtf, forType: .rtf) }
        if let html = payload.html { item.setString(html, forType: .html) }
        item.setString(payload.plain, forType: .string)
        item.setString(sourceIdentifier, forType: source)
        if transient {
            item.setData(Data(), forType: self.transient)
            item.setData(Data(), forType: autoGenerated)
        }
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }
}
